# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - mysql-up2fygjaoceju

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '8'

    - name: Build with Maven
      run: mvn clean install

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'mysql-up2fygjaoceju'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_26a85197e0f8474f8bb3412a26320995 }}
        package: '${{ github.workspace }}/target/*.jar'